#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx start
