#!/usr/bin/env bash
#creating web server and this thing is so interesting i almost forgot about the task and continue exploring

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
#testing nginx configuration
sudo nginx -t

sudo service nginx reload
