#!/usr/bin/env bash
#configure web-01 to have custom header response


#update before installing
sudo apt-get update
#installing nginx
sudo apt-get install nginx -y

#create an index page
echo "Hello World!" | sudo tee /var/www/html/index.html


# prefroming redirection

string="server_name _;\n\trewrite ^\/redirect_me htttps:\/\/.com\/mrxdoffical permanent;"

sudo sed -i"s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


# Custom http header response
sudo sed -i "/server_name _/a \ \ \ \ add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
