#!/usr/bin/env bash
# Check if the "listen 80 default_server;" line is present and correctly configured in the default site configuration file

#remove the default_server configuration file
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx

service nginx restart