#!/usr/bin/env bash
#this script displays clock

hours=0
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	min=0
	while [ $min -le 59 ]
	do
		echo "Minute: $min"
		(( min++ ))
	done
	(( hours++ ))
done